version: '3.4'

services:
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: RabbitMQ
    ports:
      - 5672:5672
      - 15672:15672

  ticketservice.api:
    image: ${DOCKER_REGISTRY-}ticketserviceapi
    container_name: Api
    build:
      context: .
      dockerfile: src/TicketService.Api/Dockerfile
    ports:
      - 3001:80
      - 3000:443

  ticketService.worker:
    image: ${DOCKER_REGISTRY-}ticketserviceworker
    container_name: Worker
    build:
      context: .
      dockerfile: src/TicketService.Worker/Dockerfile